#!/usr/bin/env python3
"""
.tflite -> C source, plus a baked-in test image for board-free inference telemetry.

Two artefacts:

  model_data.cc/.h  the quantized model as a byte array in flash.
  test_image.cc/.h  one preprocessed 96x96 int8 image, plus its expected class
                    and portion tier.

The test image is what makes the Section 8a "green" loop actually unattended:
the sketch can measure arena_used_bytes() and inference latency, and verify the
prediction is still correct, without anyone aiming the camera at a plate.

Usage:
    python3 deploy/to_c_array.py --model results/models/a075_rgb_int8.tflite
"""

import argparse
import json
import pathlib
import sys

import numpy as np

REPO = pathlib.Path(__file__).resolve().parent.parent
SKETCH = REPO / "deploy" / "nano" / "classifier_tier1"

CLASSES = ["chicken", "broccoli", "rice", "beef", "potato"]
PORTIONS = ["small", "medium", "large"]


def emit_array(data, var, dtype="unsigned char", per_line=12, align=True,
               header=None):
    lines = ["// Generated by deploy/to_c_array.py -- do not edit by hand.\n"]
    # Include our own header so these definitions pick up its `extern`
    # declarations. Without it, a namespace-scope `const` in C++ has INTERNAL
    # linkage, the .ino cannot see it, and the link fails with
    # "undefined reference to g_test_image_expected_portion".
    if header:
        lines.append(f'#include "{header}"\n\n')
    if align:
        # TFLM requires the model buffer to be 16-byte aligned or GetModel()
        # can fault on the nRF52840's stricter unaligned-access rules.
        lines.append(f'alignas(16) const {dtype} {var}[] = {{\n')
    else:
        lines.append(f"const {dtype} {var}[] = {{\n")

    body = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        body.append("  " + ", ".join(str(int(v)) for v in chunk))
    lines.append(",\n".join(body))
    lines.append("\n};\n")
    lines.append(f"const unsigned int {var}_len = {len(data)};\n")
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--channels", type=int, default=3)
    ap.add_argument("--out", default=None)
    ap.add_argument("--n-test-images", type=int, default=1)
    args = ap.parse_args()

    import tensorflow as tf

    out_dir = pathlib.Path(args.out) if args.out else SKETCH
    out_dir.mkdir(parents=True, exist_ok=True)

    blob = pathlib.Path(args.model).read_bytes()
    print(f"model: {args.model}  ({len(blob):,} bytes, "
          f"{len(blob) / 1024:.1f} KB)")

    (out_dir / "model_data.cc").write_text(
        emit_array(blob, "g_model_data", "unsigned char",
                   header="model_data.h"))
    (out_dir / "model_data.h").write_text(
        "#ifndef MODEL_DATA_H_\n#define MODEL_DATA_H_\n\n"
        "extern const unsigned char g_model_data[];\n"
        "extern const unsigned int g_model_data_len;\n\n"
        "#endif  // MODEL_DATA_H_\n")

    # ------------------------------------------------ baked-in test image(s)
    from train.data import make_dataset

    interp = tf.lite.Interpreter(model_content=blob)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    scale, zp = inp["quantization"]
    outs = {int(o["shape"][-1]): o for o in interp.get_output_details()}
    o_cls, o_por = outs[len(CLASSES)], outs[len(PORTIONS)]

    # Pull from TEST with augmentation off: this image is a correctness canary,
    # so it must be deterministic across regenerations.
    ds, _ = make_dataset("test", batch=1, channels=args.channels, training=False)

    # Pick the HIGHEST-CONFIDENCE correct image, not merely the first correct
    # one. With ~0.55 macro-F1 many predictions are near-ties, and a near-tie can
    # legitimately flip between the desktop TFLite kernels and TFLM's int8 kernels
    # without either being broken. A confident image makes the device-vs-host
    # check a real correctness signal instead of a coin toss.
    picked = []
    scanned = 0
    for x, y in ds:
        img = x.numpy()
        q = np.clip(np.round(img / scale + zp), -128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q)
        interp.invoke()
        pc = int(np.argmax(interp.get_tensor(o_cls["index"])[0]))
        pp = int(np.argmax(interp.get_tensor(o_por["index"])[0]))
        tc = int(np.argmax(y["cls"].numpy()[0]))
        tp = int(np.argmax(y["portion"].numpy()[0]))
        # Only bake in an image the host model already gets right, so a device
        # mismatch means the *device* path is broken, not the model.
        cls_probs = interp.get_tensor(o_cls["index"])[0].astype(float)
        oscale, ozp = interp.get_output_details()[0]["quantization"]
        conf = float(cls_probs.max())
        if pc == tc and pp == tp:
            picked.append({"q": q.flatten(), "cls": tc, "portion": tp,
                           "conf": conf})
        scanned += 1
        if scanned >= 400:
            break

    picked.sort(key=lambda r: -r["conf"])
    picked = picked[: args.n_test_images]

    if not picked:
        print("!! no correctly-classified test image found", file=sys.stderr)
        return 1

    p = picked[0]
    src = emit_array(p["q"], "g_test_image", "signed char", per_line=16,
                     align=False, header="test_image.h")
    src += (f"\nextern const int g_test_image_expected_cls;\n"
            f"const int g_test_image_expected_cls = {p['cls']};\n"
            f"extern const int g_test_image_expected_portion;\n"
            f"const int g_test_image_expected_portion = {p['portion']};\n")
    (out_dir / "test_image.cc").write_text(src)
    (out_dir / "test_image.h").write_text(
        "#ifndef TEST_IMAGE_H_\n#define TEST_IMAGE_H_\n\n"
        "extern const signed char g_test_image[];\n"
        "extern const unsigned int g_test_image_len;\n"
        "extern const int g_test_image_expected_cls;\n"
        "extern const int g_test_image_expected_portion;\n\n"
        "#endif  // TEST_IMAGE_H_\n")

    meta = {
        "model": str(args.model), "model_bytes": len(blob),
        "input_scale": float(scale), "input_zero_point": int(zp),
        "input_shape": [int(v) for v in inp["shape"]],
        "test_image_cls": p["cls"], "test_image_portion": p["portion"],
        "cls_output_index": int(o_cls["index"]),
        "portion_output_index": int(o_por["index"]),
    }
    (out_dir / "model_meta.json").write_text(json.dumps(meta, indent=1))

    print(f"input quantization: scale={scale:.8f} zero_point={zp}")
    print(f"baked test image  : cls={CLASSES[p['cls']]} "
          f"portion={PORTIONS[p['portion']]} conf={p['conf']:.3f} "
          f"({len(p['q'])} bytes)")
    print(f"wrote model_data.cc / test_image.cc -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
